modLoader = "javafml" #//mandatory
loaderVersion = "*" # // mandatory. Allow all forge versions as we are definding what Minecraft versions we requre later on
license = "GPLv3"
issueTrackerURL = "${issues}"


[[mods]] #//mandatory
modId = "wanparty" #//mandatory
version = "${version}" #//mandatory, gets the version number from jar populated by the build.gradle script
displayName = "${mod_name}" #//mandatory
authors = ["octi"] # Should be done with `$authors`, but architectury complains
#//updateJSONURL="https://change.me.example.invalid/updates.json" # A URL to query for updates for this mod. See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
displayURL = "${homepage}"
description = "${description}" #//mandatory. The description text for the mod
logoFile = "logo.png"
catalogueImageIcon = "icon.png"
credits = ""
#// if not set defaults to "false"
clientSideOnly = "false"
#// if not set side defaults to "BOTH"
#// TODO change to "BOTH" when we add server support
side = "BOTH"
#// Allow any version to be present (or not) on the server
acceptableRemoteVersions = "*"


[[dependencies.wanparty]]
modId = "minecraft"
mandatory = true
versionRange = "${compatible_forgemc_versions}" # Where we set what version of mc it is avalible for
ordering = "NONE"
side = "BOTH"
